---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: dlppkidev-hpa
  namespace: my-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dlppkidev-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Object
    object:
      target:
        kind: Service
        name: dlppkidev-app
      metricName: http_requests
      targetValue: 5