---
- hosts: controllers
  gather_facts: no

  tasks:

  - name: Controllers facts
    setup:
    delegate_to: "{{ item }}"
    register: controllers_facts
    with_items: "{{ groups['controllers'] }}"

- hosts: controllers
  gather_facts: yes
  become: yes

  tasks:

  - name: Installation des binaires
    copy:
      src: /vagrant_data/binaries/{{ item }}
      dest: /usr/local/bin/
      mode: 0755
      remote_src: yes
    with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kubectl

  - name: Création des répetoires
    file:
      state: directory
      path: "{{ item }}"
    with_items:
    - /etc/kubernetes/config
    - /var/lib/kubernetes/

  - name: Déploiement des certificats
    copy:
      dest: /var/lib/kubernetes/
      src: /root/enrolment/certs/{{ item }}
    with_items:
    - ca.pem
    - ca-key.pem
    - kubernetes-key.pem
    - kubernetes.pem
    - service-account-key.pem
    - service-account.pem

  - name: Déploiement de encryption-config.yaml
    copy:
      src: encryption/encryption-config.yaml
      dest: /var/lib/kubernetes/

  - name: Déploiement des configs
    copy:
      src: /root/k8s_config/{{ item }}
      dest: /var/lib/kubernetes/
    with_items:
    - kube-scheduler.kubeconfig
    - kube-controller-manager.kubeconfig

  - name: Déploiement de la config scheduler
    copy:
      src: controller/kube-scheduler.yaml
      dest: /etc/kubernetes/config/

  - name: Installation des services
    copy:
      src: controller/kube-scheduler.service
      dest: /etc/systemd/system/

  - name: Installation des services
    template:
      src: controller/{{ item }}
      dest: /etc/systemd/system/
    with_items:
    - kube-apiserver.service
    - kube-controller-manager.service

  - name: Installation de nginx
    apt:
      name: nginx

  - name: Config nginx
    copy:
      src: controller/kubernetes.default.svc.cluster.local
      dest: /etc/nginx/sites-available/

  - name: Lien symbolique
    file:
      state: link
      src: /etc/nginx/sites-available/kubernetes.default.svc.cluster.local
      dest: /etc/nginx/sites-enabled/kubernetes.default.svc.cluster.local

  - name: Démarrage des services
    systemd:
      name: kube-apiserver
      daemon_reload: yes
      enabled: yes
      state: restarted

  - name: Tempo
    pause:
      seconds: 5

  - name: Démarrage des services
    systemd:
      name: kube-controller-manager
      daemon_reload: yes
      enabled: yes
      state: restarted

  - name: Tempo
    pause:
      seconds: 5

  - name: Démarrage des services
    systemd:
      name: "{{ item }}"
      daemon_reload: yes
      enabled: yes
      state: restarted
    with_items:
    - kube-scheduler
    - nginx

  - name: Copie des configs générées
    copy:
      src: /root/k8s_config/{{ item }}
      dest: /root/
    with_items:
    - admin.kubeconfig
    - kube-controller-manager.kubeconfig
    - kube-scheduler.kubeconfig

  - name: Copie des configs cluster role
    copy:
      src: controller/{{ item }}
      dest: /root/
    with_items:
    - cluster-role.yml
    - cluster-role-binding.yml

  - name: Tempo
    pause:
      seconds: 15

  - name: Configuration cluster role
    shell: kubectl apply --kubeconfig admin.kubeconfig -f {{ item }}
    args:
      chdir: /root
    with_items:
    - cluster-role.yml
    - cluster-role-binding.yml
