---
- hosts: localhost
  gather_facts: yes
  become: yes

  tasks:

  - name: Répertoire des déploiements
    file:
      path: /root/deployments/dns
      state: directory

  - name: Configuration dns
    template:
      src: dns/kube-dns.yaml
      dest: /root/deployments/dns

  - name: Configuration dns
    template:
      src: dns/core-dns.yaml
      dest: /root/deployments/dns

#  - name: kube-dns
#    shell: kubectl create -f /root/deployments/dns/kube-dns.yaml

  - name: core-dns
    shell: kubectl apply -f /root/deployments/dns/core-dns.yaml

#  - name: core-dns
#    shell: kubectl delete --namespace=kube-system deployment kube-dns
