---
- hosts: controllers
  gather_facts: no

  tasks:

  - name: Controllers facts
    setup:
    delegate_to: "{{ item }}"
    register: controllers_facts
    with_items: "{{ groups['controllers'] }}"


- hosts: controllers
  gather_facts: yes
  become: yes

  tasks:

  - name: installation des binaires
    copy:
      src: /vagrant_data/binaries/{{ item }}
      dest: /usr/local/bin/
      mode: 0755
      remote_src: yes
    with_items:
    - etcd
    - etcdctl

  - name: Création des répertoires
    file:
      state: directory
      path: "{{ item }}"
    with_items:
    - /etc/etcd
    - /var/lib/etcd

  - name: Déploiement des certificats
    copy:
      src: /root/enrolment/certs/{{ item }}
      dest: /etc/etcd
    with_items:
    - ca.pem
    - kubernetes-key.pem
    - kubernetes.pem

  - name: etcd.service
    template:
      dest: /etc/systemd/system/etcd.service
      src: etcd/etcd.service

  - name: Service
    systemd:
      name: etcd
      daemon_reload: yes
      enabled: yes
      state: restarted