---
all:
  children:
    controllers:
      hosts:
        k8s-controller:
          ansible_host: 192.168.56.11

    workers:
      hosts:
        k8s-worker-0:
          ansible_host: 192.168.56.12

        k8s-worker-1:
          ansible_host: 192.168.56.13
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/ansible_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    public_ip: 192.168.56.11
    cluster_ip_range: 10.32.0.0/24
    internal_virtual_ip: 10.32.0.1
    cluster_cidr: 10.200.0.0/16
    cluster_dns: 10.32.0.10

    docker_registry: my-docker-registry:5443
